name: Run Postman Tests

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request: # Runs on any pull request to any branch

jobs:
  test:
    runs-on: ubuntu-latest  # The environment where the tests run

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repo into the runner

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Installs Node.js 18 (required for Newman)

      - name: Install Newman (Postman CLI)
        run: npm install -g newman  # Installs Newman globally

      - name: Run Postman Tests
        run: |
          newman run collection.json -e environment.json --reporters cli,junit --reporter-junit-export results.xml
        # Runs Postman tests using Newman and generates a JUnit XML report

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: postman-results
          path: results.xml
        # Saves the test results XML file as an artifact in GitHub Actions
